version: '2.1'
services:
  app:
    environment:
      ENV: integration
    image: basen
    ports:
    - 8080
    depends_on:
    - postgres
    links:
    - postgres

  postgres:
    build: ./dependencies/postgres
    ports:
      - 5432