version: '3'
services:
  node:
    image: registry.opensource.zalan.do/acid/patroni:1.0-SNAPSHOT
    ports:
    - 5432:5432
    - 2379
    container_name: master
#    environment:
#      PATRONI_ETCD_URL: http://etcd:2379
    command: --etcd etcd:2379
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - etcd

  debugger:
    image: quay.io/collectai/alpine-curl
    container_name: alpine
    command: watch date
    deploy:
      placement:
        constraints:
        - engine.labels.nodename == master
    networks:
    - etcd

networks:
  etcd:
    external: true
