#!/usr/bin/env bash
docker-compose down ; docker-compose up -d
JOIN_CMD=$(./remote master docker swarm init --advertise-addr $(docker inspect master |  jq -r '.[].NetworkSettings.Networks[].IPAddress') | grep 'docker swarm join' | sed s/To\ add.*//)

./remote worker1 $JOIN_CMD
./remote worker2 $JOIN_CMD

./remote master docker node ls
#./remote master docker service create --constraint engine.labels.nodename==worker1 --replicas 1 --name helloworld alpine ping docker.com

#./remote master docker service ls
#./remote master docker service ps helloworld
#./remote master docker service scale helloworld=2
#./remote master docker service ps helloworld
#./remote master docker service rm helloworld

#./remote master service create --replicas 2 --name redis --update-delay 5s redis:3.0.6
#./remote master docker service inspect --pretty redis
#./remote master docker service update --image redis:3.0.7 redis
#./remote master docker service inspect --pretty redis