#!/usr/bin/env bash
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}"))")" || exit

source include/common.sh

# Remove existing nodes
docker-compose -f compose/swarmhost.yml -f compose/swarmhost-node.yml down

# Prune volumes to reclaim disk space
docker volume prune -f

# Start dind-nodes
docker-compose -f compose/swarmhost.yml up -d

NODES=($(./get_nodes))

# Start first manager
on_node ${NODES[0]} swarm init --advertise-addr $(docker inspect node1 |  jq -r '.[].NetworkSettings.Networks[].IPAddress')

# Create join command for workers
JOIN_CMD=$(on_node ${NODES[0]} swarm join-token manager | grep 'docker swarm join' | sed s/To\ add.*// | sed s/docker\ //)

# Join workers into swarm
for NODE in ${NODES[@]:1}; do
    on_node ${NODE} ${JOIN_CMD}
done

# Create network
in_swarm network create --attachable --driver overlay swarmnet

in_swarm service create --network swarmnet --mode global --name tinytools giantswarm/tiny-tools sh -c 'while true; do sleep 60; done'
