#!/usr/bin/env bash
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}"))")" || exit

# Remove node list
rm nodelist.txt

# Store node names
echo "localhost:2376" > nodelist.txt
echo "localhost:2377" >> nodelist.txt
echo "localhost:2378" >> nodelist.txt

# Populate NODES
source include/common.sh

NODES=(`get_nodes`)

# Remove existing nodes
docker-compose -f compose/swarmhost.yml -f compose/swarmhost-node.yml down

# Start dind-nodes
docker-compose -f compose/swarmhost.yml up -d

# Start first manager
on_node ${NODES[0]} swarm init --advertise-addr $(docker inspect node1 |  jq -r '.[].NetworkSettings.Networks[].IPAddress')

# Create join command for workers
JOIN_CMD=$(on_node ${NODES[0]} swarm join-token manager | grep 'docker swarm join' | sed s/To\ add.*// | sed s/docker\ //)

# Join workers into swarm
for NODE in ${NODES[@]:1}; do
    on_node ${NODE} ${JOIN_CMD}
done

# Create network
in_swarm network create --attachable --driver overlay swarmnet

# Spin up docker registry
#in_swarm service create  --network swarmnet --name bootstrap_registry --publish 5000:5000 registry:2
#
#docker-compose -f compose/registry.yml build && docker-compose -f compose/registry.yml push
#
#in_swarm stack deploy --compose-file compose/registry.yml registry
#in_swarm service update --publish-rm 5000 bootstrap_registry
#
##in_swarm service update  registry_node
#in_swarm service update --endpoint-mode dnsrr --publish-add '5000:5000' registry_node
#in_swarm service rm bootstrap_registry
#docker-compose -f compose/registry.yml build && docker-compose -f compose/registry.yml push

#in_swarm service create --network swarmnet --mode global --name tinytools giantswarm/tiny-tools sh -c 'while true; do sleep 60; done'
