#!/usr/bin/env bash
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}"))")" || exit

# Remove node list
rm nodelist.txt

# Store node names
echo "localhost:2376" > nodelist.txt
echo "localhost:2377" >> nodelist.txt
echo "localhost:2378" >> nodelist.txt

# Populate NODES
source include/common.sh

NODES=(`get_nodes`)

# Remove existing nodes
docker-compose -f compose/swarmhost.yml down

# Start dind-nodes
docker-compose -f compose/swarmhost.yml up -d

# Start first manager
on_node ${NODES[0]} swarm init --advertise-addr $(docker inspect node1 |  jq -r '.[].NetworkSettings.Networks[].IPAddress')

# Create join command for workers
JOIN_CMD=$(on_node ${NODES[0]} swarm join-token manager | grep 'docker swarm join' | sed s/To\ add.*// | sed s/docker\ //)

# Join workers into swarm
for NODE in ${NODES[@]:1}; do
    on_node ${NODE} ${JOIN_CMD}
done

# Spin up docker registry
in_swarm service create --name registry --publish 5000:5000 registry:2

# Create network
in_swarm network create --attachable --driver overlay swarmnet
