#!/usr/bin/env bash
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}"))")" || exit

# Populate NODES
source include/common.sh

NODE_PORT=$(docker inspect $(docker-compose -f compose/swarmhost.yml -f compose/swarmhost-node.yml ps -q | head -n 1) | jq -r '.[].NetworkSettings.Ports["2375/tcp"][].HostPort')
NODE="localhost:$NODE_PORT"

SERVICES=$(on_node ${NODE} service ls --format  '{{ .Name }}')
for SERVICE in ${SERVICES}; do
    echo "Rebalancing $SERVICE"
    on_node ${NODE} service update --force ${SERVICE}
done