version: '3.3'
services:
  node:
    environment:
      ENVIRONMENTS: swarm
    image: 127.0.0.1:5000/basen
    ports:
    - 8000:8080
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      swarmnet:
        aliases:
        - app
networks:
  swarmnet:
    external: true
