version: '3.3'
services:
  node:
    image: 127.0.0.1:5000/haproxy
    build: haproxy
    environment:
      DNS_NAME: tasks.postgres
    ports:
      - 7000:7000
      - 5432:5432
      - 5433:5433
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      swarmnet:
        aliases:
        - haproxy

networks:
  swarmnet:
    external: true
