version: '3.3'
services:
  node:
    image: registry.opensource.zalan.do/acid/patroni:1.0-SNAPSHOT
    command: --etcd etcd:2379
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      endpoint_mode: dnsrr
    networks:
      swarmnet:
        aliases:
        - postgres

networks:
  swarmnet:
    external: true
