version: '3.3'
services:
  node:
    image: 127.0.0.1:5000/patroni
    build: patroni/
    environment:
      PATRONI_ETCD_URL: http://etcd:2379
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      endpoint_mode: dnsrr
    networks:
      swarmnet:
        aliases:
        - postgres

networks:
  swarmnet:
    external: true
